### ISSUE TITLE
後方互換性の為のファイルタイプ識別

### ISSUE THREAD

**Issue by sasairc** [844196/polyaness#1]
初登校です。

レコードを持たない辞書ファイルとの後方互換性を維持する為、先頭に識別子の挿入を必須にするのはどうでしょうか。

例として

``` text
file-type:polyaness<TAB>author:[AUTHOR]<TAB>description:[DESCRIPTION]
```

上記のようなレコードを先頭に置き、`file-type`の値にて識別、残りの列で辞書に関する情報を記述できれば便利かと思います。

**Comment by 844196** [comment]
読みました

**Comment by 844196** [comment]
@sasairc 

「1行目を読んでモードを切り替える」みたいな用途だと思うんですが、互換機能がないソフトウェアの場合、「1行目に`filetype:polyaness`がない場合は例外を吐いて終了」みたいな認識であってますか？

**Comment by sasairc** [comment]
@844196
そんな感じです。
互換性が無いソフトウェアの場合、どちらにせよ構文エラーで落ちると思うので。

**Comment by 844196** [comment]
@sasairc 

ども。
取り込みたいと思いますが、

![6efd54b0-s](https://cloud.githubusercontent.com/assets/4990822/12867127/ba516eda-cd28-11e5-8731-025f44a558c6.jpg)
- ファイルタイプ識別子は`filetype:polyaness_dict`でよいか？
- `filetype`以降のメタ情報はオプション扱いでよいか？

**Comment by sasairc** [comment]
@844196 

![km](https://cloud.githubusercontent.com/assets/9349287/12867198/72d725ca-cd2a-11e5-8855-cfca2620d949.gif)

> ファイルタイプ識別子はfiletype:polyaness_dictでよいか？

良いです！それでは投入！

> filetype以降のメタ情報はオプション扱いでよいか？

オプションで構いません。
ただ、`author`と`description`に関しては「推奨」扱いにした方が良いかと思います。（パッと見でわかりやすいし）

**Comment by 844196** [comment]
@sasairc 

![4521dd93](https://cloud.githubusercontent.com/assets/4990822/12867212/e60a23a8-cd2a-11e5-9c84-15785934c73b.jpg)

**Comment by sasairc** [comment]
:+1:
